name: TExTra
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - bedtools=2.31.1=hf5e1c6e_2
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_33
  - bioconductor-affy=1.64.0=r36h516909a_0
  - bioconductor-affyio=1.56.0=r36h516909a_0
  - bioconductor-annotate=1.64.0=r36_0
  - bioconductor-annotationdbi=1.48.0=r36_0
  - bioconductor-biobase=2.46.0=r36h516909a_0
  - bioconductor-biocgenerics=0.32.0=r36_0
  - bioconductor-biocparallel=1.20.0=r36he1b5a44_0
  - bioconductor-biostrings=2.54.0=r36h516909a_0
  - bioconductor-delayedarray=0.12.0=r36h516909a_0
  - bioconductor-deseq2=1.26.0=r36he1b5a44_0
  - bioconductor-genefilter=1.68.0=r36hc99cbb1_0
  - bioconductor-geneplotter=1.64.0=r36_0
  - bioconductor-genomeinfodb=1.22.0=r36_0
  - bioconductor-genomeinfodbdata=1.2.2=r36_0
  - bioconductor-genomicalignments=1.22.0=r36h516909a_0
  - bioconductor-genomicranges=1.38.0=r36h516909a_0
  - bioconductor-iranges=2.20.0=r36h516909a_0
  - bioconductor-limma=3.42.0=r36h516909a_0
  - bioconductor-preprocesscore=1.48.0=r36h516909a_0
  - bioconductor-rhtslib=1.18.0=r36hdb70ac9_1
  - bioconductor-rsamtools=2.2.0=r36he1b5a44_0
  - bioconductor-rtracklayer=1.46.0=r36h516909a_0
  - bioconductor-s4vectors=0.24.0=r36h516909a_0
  - bioconductor-singlecellexperiment=1.8.0=r36_0
  - bioconductor-summarizedexperiment=1.16.0=r36_0
  - bioconductor-vsn=3.54.0=r36h516909a_0
  - bioconductor-xvector=0.26.0=r36h516909a_0
  - bioconductor-zlibbioc=1.32.0=r36h516909a_0
  - biopython=1.83=py38h01eb140_0
  - blas=1.0=openblas
  - bwidget=1.10.1=ha770c72_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.16.0=h9f066cc_1006
  - cpc2=1.0.1=hdfd78af_0
  - curl=7.76.1=h979ede3_1
  - expat=2.6.4=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=7.5.0=habd7529_20
  - gcc_linux-64=7.5.0=h47867f9_33
  - gffcompare=0.12.6=h9948957_4
  - gffread=0.12.7=hdcf5f25_4
  - gfortran_impl_linux-64=7.5.0=h56cb351_20
  - gfortran_linux-64=7.5.0=h78c8a43_33
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.6=he838d99_2
  - gxx_impl_linux-64=7.5.0=hd0bb8aa_20
  - gxx_linux-64=7.5.0=h555fc39_33
  - harfbuzz=2.7.2=ha5b49bf_1
  - htslib=1.12=h9093b5e_1
  - icu=67.1=he1b5a44_0
  - jpeg=9e=h0b41bf4_3
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.17.2=h926e7f8_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=13_linux64_openblas
  - libcblas=3.9.0=13_linux64_openblas
  - libcurl=7.76.1=hc4aaa36_1
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=7.5.0=hda03d7c_20
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libglib=2.80.2=hf974151_0
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - liblapack=3.9.0=13_linux64_openblas
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.18=hf726d26_0
  - libopenssl-static=3.0.7=h0b41bf4_1
  - libpng=1.6.43=h2797004_0
  - libsanitizer=9.5.0=h2f262e1_19
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=7.5.0=hb016644_20
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsvm=335=h5888daf_1
  - libtiff=4.4.0=h82bc61c_5
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.9.10=h68273f3_2
  - libzlib=1.2.13=h4ab18f5_6
  - make=4.4.1=hb9d3cd8_2
  - mysql-connector-c=6.1.11=h6eb9d5d_1007
  - ncurses=6.2=h58526e2_4
  - openblas=0.3.4=h9ac9557_1000
  - openssl=1.1.1w=hd590300_0
  - pango=1.42.4=h69149e4_5
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.43=hcad00b1_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - plek=1.2=py38hfe239e1_8
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybedtools=0.10.0=py38hd638cd3_2
  - pysam=0.16.0.1=py38hf7546f9_3
  - python=3.8.12=hb7a2778_2_cpython
  - python_abi=3.8=5_cp38
  - r-acepack=1.4.1=r36h31ca83e_1006
  - r-acidbase=0.1.9=r36_0
  - r-assertthat=0.2.1=r36h6115d3f_2
  - r-backports=1.2.1=r36hcfec24a_0
  - r-base=3.6.3=hd272fe0_4
  - r-base64enc=0.1_3=r36hcfec24a_1004
  - r-bh=1.75.0_0=r36hc72bb7e_0
  - r-biocmanager=1.30.15=r36hc72bb7e_0
  - r-bioverbs=0.2.13=r36_0
  - r-bit=4.0.4=r36hcfec24a_0
  - r-bit64=4.0.5=r36hcfec24a_0
  - r-bitops=1.0_7=r36hcfec24a_0
  - r-blob=1.2.1=r36h6115d3f_1
  - r-brio=0.3.17=r36_0
  - r-cachem=1.0.5=r36hcfec24a_0
  - r-callr=3.7.0=r36hc72bb7e_0
  - r-cellranger=1.1.0=r36h6115d3f_1003
  - r-checkmate=2.0.0=r36hcdcec82_1
  - r-cli=2.5.0=r36hc72bb7e_0
  - r-clipr=0.7.1=r36h142f84f_0
  - r-cluster=2.1.0=r36h31ca83e_4
  - r-colorspace=2.0_1=r36hcfec24a_0
  - r-cpp11=0.2.7=r36hc72bb7e_0
  - r-crayon=1.4.1=r36hc72bb7e_0
  - r-curl=4.3.1=r36hcfec24a_0
  - r-data.table=1.14.0=r36hcfec24a_0
  - r-dbi=1.1.1=r36hc72bb7e_0
  - r-desc=1.3.0=r36hc72bb7e_0
  - r-diffobj=0.3.4=r36hcfec24a_0
  - r-digest=0.6.27=r36h03ef668_0
  - r-ellipsis=0.3.2=r36hcfec24a_0
  - r-evaluate=0.14=r36h6115d3f_2
  - r-fansi=0.4.2=r36hcfec24a_0
  - r-farver=2.1.0=r36h03ef668_0
  - r-fastmap=1.1.0=r36h03ef668_0
  - r-forcats=0.5.1=r36hc72bb7e_0
  - r-foreign=0.8_76=r36hcdcec82_1
  - r-formatr=1.9=r36hc72bb7e_0
  - r-formula=1.2_4=r36h142f84f_0
  - r-futile.logger=1.4.3=r36h6115d3f_1003
  - r-futile.options=1.0.1=r36h6115d3f_1002
  - r-gdata=2.18.0=r36h6115d3f_1003
  - r-ggplot2=3.3.3=r36hc72bb7e_0
  - r-ggrepel=0.9.1=r36h03ef668_0
  - r-glue=1.4.2=r36hcfec24a_0
  - r-goalie=0.4.4=r36_0
  - r-gridextra=2.3=r36h6115d3f_1003
  - r-gtable=0.3.0=r36h6115d3f_3
  - r-gtools=3.8.2=r36hcdcec82_1
  - r-haven=2.4.1=r36h2713e49_0
  - r-hexbin=1.28.1=r36h31ca83e_2
  - r-highr=0.9=r36hc72bb7e_0
  - r-hmisc=4.4_1=r36h31ca83e_1
  - r-hms=1.1.0=r36hc72bb7e_0
  - r-htmltable=2.2.1=r36hc72bb7e_0
  - r-htmltools=0.5.1.1=r36h03ef668_0
  - r-htmlwidgets=1.5.3=r36hc72bb7e_0
  - r-isoband=0.2.4=r36h03ef668_0
  - r-jpeg=0.1_8.1=r36hcdcec82_1
  - r-jsonlite=1.7.2=r36hcfec24a_0
  - r-knitr=1.33=r36hc72bb7e_0
  - r-labeling=0.4.2=r36h142f84f_0
  - r-lambda.r=1.2.4=r36h6115d3f_1
  - r-lattice=0.20_44=r36hcfec24a_0
  - r-latticeextra=0.6_29=r36h6115d3f_1
  - r-lifecycle=1.0.0=r36hc72bb7e_0
  - r-locfit=1.5_9.4=r36hcdcec82_1
  - r-magrittr=2.0.1=r36hcfec24a_1
  - r-markdown=1.1=r36hcfec24a_1
  - r-mass=7.3_54=r36hcfec24a_0
  - r-matrix=1.3_3=r36he454529_0
  - r-matrixstats=0.58.0=r36hcfec24a_0
  - r-memoise=2.0.0=r36hc72bb7e_0
  - r-mgcv=1.8_35=r36he454529_0
  - r-mime=0.10=r36hcfec24a_0
  - r-munsell=0.5.0=r36h6115d3f_1003
  - r-nlme=3.1_150=r36h31ca83e_0
  - r-nnet=7.3_16=r36hcfec24a_0
  - r-openxlsx=4.2.3=r36h1b71b39_0
  - r-pheatmap=1.0.12=r36h6115d3f_2
  - r-pillar=1.6.1=r36hc72bb7e_0
  - r-pkgconfig=2.0.3=r36h6115d3f_1
  - r-pkgload=1.2.1=r36h03ef668_0
  - r-plogr=0.2.0=r36h6115d3f_1003
  - r-png=0.1_7=r36hcfec24a_1004
  - r-praise=1.0.0=r36h6115d3f_1004
  - r-prettyunits=1.1.1=r36h6115d3f_1
  - r-processx=3.5.2=r36hcfec24a_0
  - r-progress=1.2.2=r36h6115d3f_2
  - r-ps=1.6.0=r36hcfec24a_0
  - r-purrr=0.3.4=r36hcfec24a_1
  - r-r.methodss3=1.8.1=r36h6115d3f_0
  - r-r.oo=1.24.0=r36h6115d3f_0
  - r-r.utils=2.10.1=r36h6115d3f_0
  - r-r6=2.5.0=r36hc72bb7e_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_1003
  - r-rcpp=1.0.6=r36h03ef668_0
  - r-rcpparmadillo=0.10.4.0.0=r36h306847c_0
  - r-rcurl=1.98_1.3=r36hcfec24a_0
  - r-readr=1.4.0=r36h1b71b39_0
  - r-readxl=1.3.1=r36hde08347_4
  - r-rematch=1.0.1=r36h6115d3f_1003
  - r-rematch2=2.1.2=r36h6115d3f_1
  - r-rio=0.5.26=r36hc72bb7e_0
  - r-rlang=0.4.11=r36hcfec24a_0
  - r-rpart=4.1_15=r36hcfec24a_2
  - r-rprojroot=2.0.2=r36hc72bb7e_0
  - r-rsqlite=2.2.5=r36h03ef668_0
  - r-rstudioapi=0.13=r36hc72bb7e_0
  - r-scales=1.1.1=r36h6115d3f_0
  - r-snow=0.4_3=r36h6115d3f_1002
  - r-stringi=1.5.3=r36hca8494e_0
  - r-stringr=1.4.0=r36h6115d3f_2
  - r-survival=3.2_11=r36hcfec24a_0
  - r-testthat=3.0.2=r36h03ef668_0
  - r-tibble=3.1.2=r36hcfec24a_0
  - r-tidyselect=1.1.1=r36hc72bb7e_0
  - r-transformer=0.2.12=r36_0
  - r-utf8=1.2.1=r36hcfec24a_0
  - r-vctrs=0.3.8=r36hcfec24a_1
  - r-viridis=0.6.1=r36hc72bb7e_0
  - r-viridislite=0.4.0=r36hc72bb7e_0
  - r-waldo=0.2.5=r36hc72bb7e_0
  - r-withr=2.4.2=r36hc72bb7e_0
  - r-xfun=0.23=r36hcfec24a_0
  - r-xml=3.99_0.3=r36hcdcec82_1
  - r-xtable=1.8_4=r36h6115d3f_3
  - r-yaml=2.2.1=r36hcfec24a_1
  - r-zip=2.1.1=r36hcfec24a_0
  - readline=8.1=h46c0cb4_0
  - samtools=1.12=h9aed4be_1
  - sed=4.8=he412f7d_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sqlite=3.37.0=h9cd32fc_0
  - star=2.7.10b=h9ee0642_0
  - stringtie=2.2.1=h3198e80_0
  - subread=2.0.6=he4a0461_2
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - tzdata=2025a=h78e105d_0
  - ucsc-bedgraphtobigwig=472=h9b8f530_1
  - wheel=0.45.1=pyhd8ed1ab_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.11=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==0.15.0
      - arviz==0.11.0
      - astunparse==1.6.3
      - certifi==2025.1.31
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - fastprogress==1.0.3
      - flatbuffers==1.12
      - fonttools==4.56.0
      - gast==0.3.3
      - google-auth==2.47.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.32.0
      - h5py==2.10.0
      - idna==3.11
      - importlib-metadata==8.5.0
      - joblib==1.4.2
      - keras==2.4.3
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.7
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.6.3
      - netcdf4==1.7.2
      - numpy==1.19.5
      - oauthlib==3.3.1
      - opt-einsum==3.3.0
      - packaging==24.2
      - pandas==1.4.4
      - patsy==1.0.1
      - pillow==10.4.0
      - protobuf==3.20.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pymc3==3.9.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scipy==1.10.1
      - six==1.15.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.4.1
      - tensorflow-estimator==2.4.0
      - termcolor==1.1.0
      - theano==1.0.5
      - typing-extensions==3.7.4.3
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - wrapt==1.12.1
      - xarray==2022.9.0
      - zipp==3.20.2